/**
 * @file operationship-protocol/src/index.ts
 * @description Master JSON Schema and TypeScript Interfaces for OperationShip.
 * This file acts as the ultimate source of truth for the AI outputs and UI rendering.
 */

// ==========================================
// 1. CORE SYSTEM ENUMS & TYPES
// ==========================================

export type NodeStatus = 'active' | 'ghost'; 
export type FeatureTier = 'free' | 'pro'; 
export type EdgeFlowType = 'capital' | 'physical' | 'digital' | 'labor' | 'information';

/**
 * Categorized explicitly so the UI renderer (operationship-web) 
 * can map exact SVG assets to these specific strings.
 */
export type NodeType = 
  | 'supplier' 
  | 'manufacturer' 
  | 'warehouse' 
  | 'logistics' 
  | 'marketing' 
  | 'customer' 
  | 'revenue' 
  | 'automation' 
  | 'sustainability' 
  | 'tax_optimization'
  | 'waste_utilization'
  | 'custom'; // Fallback for highly unique AI suggestions

// ==========================================
// 2. FINANCIAL & ANALYTICAL METRICS
// ==========================================

/**
 * Activated via the "Unit Economics" toggle. 
 * Provides deep simulation data without breaking the standard graph view.
 */
export interface UnitEconomics {
  monthlyCost: number;     
  monthlyRevenue: number;  
  margin?: number;         // Automatically calculated gross margin percentage
  riskScore: number;       // 0 to 10 scale (Triggers UI warnings if > 7)
  efficiencyRating: number;// 0 to 100 percentage
}

/**
 * High-tier strategic insights generated by the AI for specific nodes.
 * This populates the "Master-Level" sidebar when a user clicks the left button.
 */
export interface MasterInsights {
  automationOpportunity?: string; // e.g., "Replace manual QA with AI vision"
  wasteMonetization?: string;     // e.g., "Sell offcut leather to local artisans"
  failureWarning?: string;        // e.g., "Single supplier dependency detected"
  taxStrategy?: string;           // Legal optimization suggestions
}

// ==========================================
// 3. REACT FLOW DATA STRUCTURES
// ==========================================

/**
 * Contains ALL the business logic for a single node.
 * React Flow isolates UI coordinates from business data, and so do we.
 */
export interface OperationNodeData {
  title: string;
  description: string;           // Core explanation of effectiveness/efficiency
  status: NodeStatus;            // Determines if it renders as a Ghost Node
  tierRequired: FeatureTier;     // Gates features for Stripe integration
  isSelected: boolean;           // UI State: True when @mentioned in chat
  metrics?: UnitEconomics;       // Injected when Unit Economics is ON
  insights?: MasterInsights;     // The "Brutal Realism" strategic data
}

/**
 * The strict definition of a Node in OperationShip.
 * Completely compatible with React Flow's node architecture.
 */
export interface OperationNode {
  id: string;                    // e.g., 'node_logistics_1'
  type: NodeType;                
  position: { x: number; y: number }; // Canvas coordinates
  data: OperationNodeData;
}

/**
 * Represents the flow and relationship between two nodes.
 */
export interface OperationEdge {
  id: string;                    // e.g., 'edge_supp_to_mfg'
  source: string;                // Origin Node ID
  target: string;                // Destination Node ID
  label?: string;                // Rendered text on the connection line
  animated?: boolean;            // UI State: Flows when timeline/simulation is active
  type?: 'smoothstep' | 'straight' | 'bezier'; // Line routing style
  data?: {
    flowType: EdgeFlowType;
    flowVolume?: number;         // Used for timeline simulation (e.g., 500 units/day)
    isBottleneck: boolean;       // If true, the UI renders this line red/orange
  };
}

// ==========================================
// 4. MASTER GRAPH (THE SAVED PROJECT)
// ==========================================

/**
 * The complete system state saved to localStorage (and eventually the cloud).
 * Includes versioning to ensure future-proofing.
 */
export interface OperationGraph {
  schemaVersion: string;         // e.g., "1.0.0" - Crucial for future data migrations
  projectId: string;
  projectName: string;
  createdAt: string;             // ISO Timestamp
  updatedAt: string;             // ISO Timestamp
  
  // Simulation Context
  region: string;                // e.g., 'India', 'USA'
  flexibilityScore: number;      // 0 to 10 scale
  
  // Toggle States
  toggles: {
    unitEconomicsActive: boolean;
    sustainabilityActive: boolean;
  };
  
  // The Architecture
  nodes: OperationNode[];
  edges: OperationEdge[];
}
